### PR TITLE
qa-midrc DICOM viewer link

### PR DESCRIPTION
**Pull request by paulineribeyre**
Link to Jira ticket if there is one:

### Environments
qa-midrc

### Description of changes
DICOM viewer link
"portal": "quay.io/cdis/data-portal:feat_dicom-link",

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-midrc.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-midrc.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Review by haraprasadj — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-midrc.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-midrc.planx-pla.net/manifest.json
## :warning: Services on branch
- dicom-viewer
- portal

**Pull request merged**
