### PR TITLE
remove mariner from manifests

### PR DESCRIPTION
**Pull request by haraprasadj**
Link to Jira ticket if there is one:

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-genomel.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-new.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-mickey.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [patients] in explorerConfig.guppyConfig.dataType not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Birth] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Death] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [DeceasedFlag] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Gene] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.DaysFromAnchorDateToBxDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Radiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Chemotherapy] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToDiagnosisDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Gradedifferentiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Laterality] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Stagegroupbest] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.RadiationsurgerySequence] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Histologyicdo3X] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Lymphvascularinvasionl] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SeerSummaryStage2000] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.PhysiciansStage] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToMostdefinitivesurgDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ChemotherapyFac] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.TumorSize] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SequenceNumber] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [file_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [file_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- ssjdispatcher
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-brain.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-genomel.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-new.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-niaid.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- requestor
# jenkins-perf.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard

**Review by jingh8 — APPROVED** [review]

**Review by jingh8 — APPROVED** [review]

**Review by atharvar28 — APPROVED** [review]

**Pull request merged**
