### PR TITLE
Heal add to browser

### PR DESCRIPTION
**Pull request by jmontmaxwell**
Link to Jira ticket if there is one:

### Description of changes
Adding .html and .png files for static notebooks

### CODE REVIEW

**Review by haraprasadj — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Pull request merged**
