### PR TITLE
use mds version 1.6.1

### PR DESCRIPTION
**Pull request by haraprasadj**
Link to Jira ticket if there is one:

### CODE REVIEW

**Review by mfshao — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- hatchery

**Comment by mfshao** [comment]
fyi you could also pin portal to `3.13.0` if you like

**Comment by haraprasadj** [comment]
> fyi you could also pin portal to `3.13.0` if you like

will do 👍🏼

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- hatchery

**Pull request merged**
