### PR TITLE
Reduce qa.planx-pla.net footprint

### PR DESCRIPTION
**Pull request by haraprasadj**
Link to Jira ticket if there is one:

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- thor

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- thor

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- thor

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- thor
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
  - Use "discoveryUseAggWTS" in "featureFlags" to enable "True Access" for aggregate discovery (https://github.com/uc-cdis/data-portal/pull/1089)
  - "True Access" for aggregate discovery depends on [WTS 0.4.0+](https://github.com/uc-cdis/workspace-token-service/releases/tag/0.4.0]) (https://github.com/uc-cdis/data-portal/pull/1089)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (https://github.com/uc-cdis/data-portal/pull/1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (https://github.com/uc-cdis/data-portal/pull/1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (https://github.com/uc-cdis/data-portal/pull/1067)
  - Discovery component will now require a `supportedValues` section in its `discoveryConfig.features.authorization` config (e.g. https://github.com/uc-cdis/cdis-manifest/pull/5138, see testing in qa-heal https://ctds-planx.atlassian.net/browse/BRH-254) (https://github.com/uc-cdis/data-portal/pull/1089)
  - Discovery component will now require a `studies` section in its `discoveryConfig` config, by default it can be a empty list `[]`, fro example: `"studies: []"` (https://github.com/uc-cdis/data-portal/pull/1089)

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- thor
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
  - Use "discoveryUseAggWTS" in "featureFlags" to enable "True Access" for aggregate discovery (https://github.com/uc-cdis/data-portal/pull/1089)
  - "True Access" for aggregate discovery depends on [WTS 0.4.0+](https://github.com/uc-cdis/workspace-token-service/releases/tag/0.4.0]) (https://github.com/uc-cdis/data-portal/pull/1089)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (https://github.com/uc-cdis/data-portal/pull/1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (https://github.com/uc-cdis/data-portal/pull/1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (https://github.com/uc-cdis/data-portal/pull/1067)
  - Discovery component will now require a `supportedValues` section in its `discoveryConfig.features.authorization` config (e.g. https://github.com/uc-cdis/cdis-manifest/pull/5138, see testing in qa-heal https://ctds-planx.atlassian.net/browse/BRH-254) (https://github.com/uc-cdis/data-portal/pull/1089)
  - Discovery component will now require a `studies` section in its `discoveryConfig` config, by default it can be a empty list `[]`, fro example: `"studies: []"` (https://github.com/uc-cdis/data-portal/pull/1089)

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- thor
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
  - Use "discoveryUseAggWTS" in "featureFlags" to enable "True Access" for aggregate discovery (https://github.com/uc-cdis/data-portal/pull/1089)
  - "True Access" for aggregate discovery depends on [WTS 0.4.0+](https://github.com/uc-cdis/workspace-token-service/releases/tag/0.4.0]) (https://github.com/uc-cdis/data-portal/pull/1089)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (https://github.com/uc-cdis/data-portal/pull/1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (https://github.com/uc-cdis/data-portal/pull/1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (https://github.com/uc-cdis/data-portal/pull/1067)
  - Discovery component will now require a `supportedValues` section in its `discoveryConfig.features.authorization` config (e.g. https://github.com/uc-cdis/cdis-manifest/pull/5138, see testing in qa-heal https://ctds-planx.atlassian.net/browse/BRH-254) (https://github.com/uc-cdis/data-portal/pull/1089)
  - Discovery component will now require a `studies` section in its `discoveryConfig` config, by default it can be a empty list `[]`, fro example: `"studies: []"` (https://github.com/uc-cdis/data-portal/pull/1089)

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- thor
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
  - Use "discoveryUseAggWTS" in "featureFlags" to enable "True Access" for aggregate discovery (https://github.com/uc-cdis/data-portal/pull/1089)
  - "True Access" for aggregate discovery depends on [WTS 0.4.0+](https://github.com/uc-cdis/workspace-token-service/releases/tag/0.4.0]) (https://github.com/uc-cdis/data-portal/pull/1089)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (https://github.com/uc-cdis/data-portal/pull/1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (https://github.com/uc-cdis/data-portal/pull/1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (https://github.com/uc-cdis/data-portal/pull/1067)
  - Discovery component will now require a `supportedValues` section in its `discoveryConfig.features.authorization` config (e.g. https://github.com/uc-cdis/cdis-manifest/pull/5138, see testing in qa-heal https://ctds-planx.atlassian.net/browse/BRH-254) (https://github.com/uc-cdis/data-portal/pull/1089)
  - Discovery component will now require a `studies` section in its `discoveryConfig` config, by default it can be a empty list `[]`, fro example: `"studies: []"` (https://github.com/uc-cdis/data-portal/pull/1089)

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- qabot
- thor
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- peregrine
  - Peregrine does not rely on configuration files in the cloud-automation repository anymore. The Peregrine configuration files are in the Peregrine repository. (https://github.com/uc-cdis/peregrine/pull/191)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
  - Use "discoveryUseAggWTS" in "featureFlags" to enable "True Access" for aggregate discovery (https://github.com/uc-cdis/data-portal/pull/1089)
  - "True Access" for aggregate discovery depends on [WTS 0.4.0+](https://github.com/uc-cdis/workspace-token-service/releases/tag/0.4.0]) (https://github.com/uc-cdis/data-portal/pull/1089)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (https://github.com/uc-cdis/data-portal/pull/1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (https://github.com/uc-cdis/data-portal/pull/1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (https://github.com/uc-cdis/data-portal/pull/1067)
  - Discovery component will now require a `supportedValues` section in its `discoveryConfig.features.authorization` config (e.g. https://github.com/uc-cdis/cdis-manifest/pull/5138, see testing in qa-heal https://ctds-planx.atlassian.net/browse/BRH-254) (https://github.com/uc-cdis/data-portal/pull/1089)
  - Discovery component will now require a `studies` section in its `discoveryConfig` config, by default it can be a empty list `[]`, fro example: `"studies: []"` (https://github.com/uc-cdis/data-portal/pull/1089)

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- qabot
- thor
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- peregrine
  - Peregrine does not rely on configuration files in the cloud-automation repository anymore. The Peregrine configuration files are in the Peregrine repository. (https://github.com/uc-cdis/peregrine/pull/191)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
  - Use "discoveryUseAggWTS" in "featureFlags" to enable "True Access" for aggregate discovery (https://github.com/uc-cdis/data-portal/pull/1089)
  - "True Access" for aggregate discovery depends on [WTS 0.4.0+](https://github.com/uc-cdis/workspace-token-service/releases/tag/0.4.0]) (https://github.com/uc-cdis/data-portal/pull/1089)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (https://github.com/uc-cdis/data-portal/pull/1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (https://github.com/uc-cdis/data-portal/pull/1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (https://github.com/uc-cdis/data-portal/pull/1067)
  - Discovery component will now require a `supportedValues` section in its `discoveryConfig.features.authorization` config (e.g. https://github.com/uc-cdis/cdis-manifest/pull/5138, see testing in qa-heal https://ctds-planx.atlassian.net/browse/BRH-254) (https://github.com/uc-cdis/data-portal/pull/1089)
  - Discovery component will now require a `studies` section in its `discoveryConfig` config, by default it can be a empty list `[]`, fro example: `"studies: []"` (https://github.com/uc-cdis/data-portal/pull/1089)

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- qabot
- thor
## Deployment changes
- fence
  - Requires a Fence DB migration (https://github.com/uc-cdis/fence/pull/1068)
  - Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET` (https://github.com/uc-cdis/fence/pull/1051)
  - B/c the default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP, you MUST ensure that an instance that should comply with FedRAMP does NOT override this fence configuration (e.g. it should be 15 minutes) `SESSION_TIMEOUT: 900` (https://github.com/uc-cdis/fence/pull/1040)
- peregrine
  - Peregrine does not rely on configuration files in the cloud-automation repository anymore. The Peregrine configuration files are in the Peregrine repository. (https://github.com/uc-cdis/peregrine/pull/191)
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)
  - Use "discoveryUseAggWTS" in "featureFlags" to enable "True Access" for aggregate discovery (https://github.com/uc-cdis/data-portal/pull/1089)
  - "True Access" for aggregate discovery depends on [WTS 0.4.0+](https://github.com/uc-cdis/workspace-token-service/releases/tag/0.4.0]) (https://github.com/uc-cdis/data-portal/pull/1089)
- sheepdog
  - Sheepdog does not rely on configuration files in the cloud-automation repository anymore. The Sheepdog configuration files are in the Sheepdog repository. (https://github.com/uc-cdis/sheepdog/pull/387)
## Breaking changes
- arborist
  - The `GET /auth/mapping` endpoint does not accept `username` as a query parameter anymore. It only supports parsing the username from the provided JWT. To specify a username, use the `POST /auth/mapping` endpoint. (https://github.com/uc-cdis/arborist/pull/153)
- fence
  - Default session expiration changed from 30 minutes to 15 minutes to comply with FedRAMP (https://github.com/uc-cdis/fence/pull/1040)
- portal
  - Replaced loading  the data in  `iframes` in Workspace page with Redirect component. (https://github.com/uc-cdis/data-portal/pull/1067)
  - Deprecating the use of `default-workspaces` i. e an individual commons will no longer be able to deploy standalone jupyterhub images, they may use [hatchery service](https://github.com/uc-cdis/hatchery) instead. (https://github.com/uc-cdis/data-portal/pull/1067)
  - `studyRegistrationConfig` in `gitops.json` must now be placed within the `regsitrationConfigs.features` block [[Refer this PR](https://github.com/uc-cdis/cdis-manifest/pull/5095)] (https://github.com/uc-cdis/data-portal/pull/1067)
  - Discovery component will now require a `supportedValues` section in its `discoveryConfig.features.authorization` config (e.g. https://github.com/uc-cdis/cdis-manifest/pull/5138, see testing in qa-heal https://ctds-planx.atlassian.net/browse/BRH-254) (https://github.com/uc-cdis/data-portal/pull/1089)
  - Discovery component will now require a `studies` section in its `discoveryConfig` config, by default it can be a empty list `[]`, fro example: `"studies: []"` (https://github.com/uc-cdis/data-portal/pull/1089)

**Review by atharvar28 — APPROVED** [review]

**Pull request merged**
