### PR TITLE
BDCat_DD_4.0.3

### PR DESCRIPTION
**Pull request by svburke**
Link to Jira ticket if there is one:

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata
- dashboard

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata
- dashboard

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata
- dashboard

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata
- dashboard

**Review by themarcelor — APPROVED** [review]
+1

**Pull request merged**
