### PR TITLE
chore:Enabling study-viewer in jenkins-niaid

### PR DESCRIPTION
**Pull request by atharvar28**
Enable study_viewer in jenkins

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# jenkins-niaid.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Review by mfshao — APPROVED** [review]

**Review by themarcelor — APPROVED** [review]
+1 🏆

**Comment by PlanXCyborg** [comment]
# jenkins-niaid.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Comment by PlanXCyborg** [comment]
# jenkins-niaid.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Comment by PlanXCyborg** [comment]
# jenkins-niaid.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Comment by PlanXCyborg** [comment]
# jenkins-niaid.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Review by themarcelor — APPROVED** [review]
+1 approving again.
AWESOME! 🏆

**Pull request merged**
