### PR TITLE
updated ETL mapping v1 with paired back core measure DD

### PR DESCRIPTION
**Pull request by mbkranz**
### Environments
QA
### Description of changes
selected a subset of core measure sections and items for initial dev of explorer page etc

### CODE REVIEW

**Review by paulineribeyre — DISMISSED** [review]

**Comment by mbkranz** [comment]
@paulineribeyre  Yup - Will change the gitops.json next -- although why is it not finding `project_id`?

**Comment by paulineribeyre** [comment]
the "project_id" ones have been failing for a bit, so it's not related to your changes, i'm not sure what's up https://github.com/uc-cdis/gitops-qa/pull/1967#issuecomment-1102984313

**Review by haraprasadj — COMMENTED** [review]
This is the error from the ETL logs in the CI run
```
2022-05-11 16:58:46,108 ERROR tool.ImportAllTablesTool: Encountered IOException running import job: java.io.IOException: psql terminated with status 2
ERROR when running transformation
Traceback (most recent call last):
  File "run_etl.py", line 31, in run_transform
    translators = interpreter.create_translators(sc, config)
  File "/tube/tube/etl/indexers/interpreter.py", line 18, in create_translators
    sc, config.HDFS_DIR, writer, m, model, dictionary
  File "/tube/tube/etl/indexers/aggregation/translator.py", line 75, in __init__
    self.parser = Parser(mapping, model, dictionary)
  File "/tube/tube/etl/indexers/aggregation/parser.py", line 54, in __init__
    self.get_direct_children() if "flatten_props" in mapping else []
  File "/tube/tube/etl/indexers/aggregation/parser.py", line 348, in get_direct_children
    child_label, edge = get_edge_table(self.model, self.root, child["path"])
  File "/tube/tube/utils/dd.py", line 27, in get_edge_table
    edge = getattr(node, edge_name)
AttributeError: type object 'Participant' has no attribute 'time_points.substance_uses'
```

**Comment by paulineribeyre** [comment]
@haraprasadj we're discussing that in this thread, if you have any ideas what's wrong: 🙏  https://cdis.slack.com/archives/C0292AVGE3A/p1651261307722709

**Comment by mbkranz** [comment]
@paulineribeyre  @haraprasadj  

I thought of a solution that will satisfy my use case (and actually may be better than using a flatten props with dot syntax). That is, making another mapping centered on the child node from above (time points) and use parent props for the participant level and flatten props for the grandchild (no need for dot syntax now).

I'll add another comment when I commit this change

**Comment by paulineribeyre** [comment]
@mbkranz just merged this: https://github.com/uc-cdis/gitops-qa/pull/2005
i will test it in QA

**Comment by paulineribeyre** [comment]
```
Exception: something bad has just happened
the properties '[{'name': 'S3a_category'}, {'name': 'S4a_category'}, {'name': 'S4f_category'}, {'name': 'S4g_category'}, {'name': 'S4h_category'}, {'name': 'S4j_category'}, {'name': 'S1a'}, {'name': 'S1b'}, {'name': 'S2a'}, {'name': 'S2b'}, {'name': 'S2c'}, {'name': 'S3a'}, {'name': 'S3b'}, {'name': 'S4a'}, {'name': 'S4b'}, {'name': 'S4f'}, {'name': 'S4g'}, {'name': 'S4h'}, {'name': 'S4j'}, {'name': 'S4k'}]' for 'substance_uses'
for parent 'substance_use'
has multiplicity 'many_to_one' that cannot be used on in 'flatten_props'
```

**Comment by mbkranz** [comment]
@paulineribeyre  It appears this error occurred because substance use has a many_to_one link to time points. This is incorrect as all children of time point should be one_to_one. I will submit a PR for the JCOIN data dictionary to change this. After this is deployed, the flatten props should work.

**Comment by mbkranz** [comment]
> @paulineribeyre It appears this error occurred because substance use has a many_to_one link to time points. This is incorrect as all children of time point should be one_to_one. I will submit a PR for the JCOIN data dictionary to change this. After this is deployed, the flatten props should work.

@paulineribeyre  Thanks for deploying the DD-- did this solve the problem?

**Pull request closed without merging**
