### PR TITLE
Update etlMapping.yaml

### PR DESCRIPTION
**Pull request by svburke**
Link to Jira ticket if there is one:

### Description of changes
Switch from ParentProps to injecting props

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [submitter_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [submitter_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [submitter_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [submitter_id] in explorerConfig.table.fields not found in etlMapping

**Review by themarcelor — APPROVED** [review]
+1

**Pull request merged**
