### PR TITLE
Updating CI env with 2022.04 qa-jcoin.planx-pla.net 1649349208

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2022.04 to qa-jcoin.planx-pla.net

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net/manifest.json
## Deployment changes
- wts
  - This version of WTS requires a DB migration (in cloud-automation deployments, the DB should be migrated automatically) (uc-cdis/workspace-token-service#40)

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Review by paulineribeyre — APPROVED** [review]

**Pull request merged**
