### PR TITLE
chore: adding new jenkins envs

### PR DESCRIPTION
**Pull request by atharvar28**
GQE-12 (https://ctds-planx.atlassian.net/browse/GQE-12)

### CODE REVIEW

**Review by haraprasadj — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# jenkins-new-1.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping
- Field error: Field [breed] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [auth_resource_path] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [disease_type] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-new-2.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping
- Field error: Field [breed] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [auth_resource_path] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [disease_type] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-new-3.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping
- Field error: Field [breed] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [auth_resource_path] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [disease_type] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-new-4.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [node_id] in explorerConfig.charts not found in etlMapping
- Field error: Field [breed] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [auth_resource_path] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [disease_type] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-new-1.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-new-2.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-new-3.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Review by haraprasadj — APPROVED** [review]
+1

**Pull request merged**
