### PR TITLE
Move all qa envs behind VPN

### PR DESCRIPTION
**Pull request by jawadqur**
Link to Jira ticket if there is one:

https://ctds-planx.atlassian.net/browse/GPE-109 

### Environments
all non-prod environments

### Description of changes
Move all non-prod environments behind VPN.

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-bloodpac.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-canine.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-ibd.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: rowAccessor [project_id] not found in index with type project

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-mickey.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [patients] in explorerConfig.guppyConfig.dataType not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Birth] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Days_To_Death] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [DeceasedFlag] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.Gene] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [ActionableMutations.DaysFromAnchorDateToBxDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Radiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Chemotherapy] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToDiagnosisDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Gradedifferentiation] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Laterality] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Stagegroupbest] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.RadiationsurgerySequence] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Histologyicdo3X] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Lymphvascularinvasionl] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SeerSummaryStage2000] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.PhysiciansStage] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.DaysFromAnchorDateToMostdefinitivesurgDate] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ChemotherapyFac] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.TumorSize] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [Oncology_Primary.SequenceNumber] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Race] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Ethnicity] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Gender] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [ActionableMutations.Lab] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.Multiplicitycounter] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [Oncology_Primary.ICDOSite] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [file_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [file_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-midrc.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [modality] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer_model_name] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [series_description] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [slice_thickness] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [spacing_between_slices] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_category] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [implementation_class_uid] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [implementation_version_name] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [transfer_syntax_uid] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [image_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [body_part_examined] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [view_position] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [contrast_bolus_agent_number] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [lossy_image_compression] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [manufacturer_model_name] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [series_description] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [slice_thickness] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [spacing_between_slices] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [modality] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_category] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [implementation_class_uid] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [implementation_version_name] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [transfer_syntax_uid] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [image_type] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [body_part_examined] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [view_position] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [contrast_bolus_agent_number] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [lossy_image_compression] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [modality] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer_model_name] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [series_description] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [slice_thickness] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [spacing_between_slices] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_category] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [implementation_class_uid] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [implementation_version_name] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [transfer_syntax_uid] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [image_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [body_part_examined] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [view_position] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [contrast_bolus_agent_number] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [lossy_image_compression] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [manufacturer_model_name] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [series_description] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [slice_thickness] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [spacing_between_slices] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [modality] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_category] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [implementation_class_uid] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [implementation_version_name] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [transfer_syntax_uid] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [image_type] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [body_part_examined] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [view_position] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [contrast_bolus_agent_number] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [lossy_image_compression] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [modality] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer_model_name] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [series_description] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [slice_thickness] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [spacing_between_slices] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_category] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [implementation_class_uid] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [implementation_version_name] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [transfer_syntax_uid] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [image_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [body_part_examined] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [view_position] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [contrast_bolus_agent_number] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [lossy_image_compression] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [manufacturer] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [manufacturer_model_name] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [series_description] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [slice_thickness] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [spacing_between_slices] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [modality] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_category] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [implementation_class_uid] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [implementation_version_name] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [transfer_syntax_uid] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [image_type] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [body_part_examined] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [view_position] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [contrast_bolus_agent_number] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [lossy_image_compression] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-tb.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-brain.planx-pla.net/manifest.json
## :warning: Services on branch
- manifestservice
- arborist
- dashboard
- hatchery
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- ssjdispatcher
- spark
- tube
- guppy
- wts
- metadata
# qa-canine.planx-pla.net/manifest.json
## :warning: Services on branch
- revproxy
- dashboard
- metadata
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
# qa-dcfdemo.planx-pla.net/manifest.json
## :warning: Services on branch
- revproxy
- dashboard
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- hatchery
# qa-mickey.planx-pla.net/manifest.json
## :warning: Services on branch
- cohort-middleware
- mariner
- ohdsi-atlas
- ohdsi-webapi
- portal
# qa-niaid.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- acronymbot
- cogwheel
- jenkins
# qaplanetv2.planx-pla.net/manifest.json
## :warning: Services on branch
- revproxy
- tube

**Review by haraprasadj — APPROVED** [review]

**Review by paulineribeyre — APPROVED** [review]

**Review by atharvar28 — APPROVED** [review]

**Pull request merged**
