### PR TITLE
Gen3 Monthly Release 2021.07 qa-heal.planx-pla.net 1625147491

### PR DESCRIPTION
**Pull request by themarcelor**
Applying version 2021.07 to qa-heal.planx-pla.net

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
## Deployment changes
- audit-service
  - **If a previous version of the audit service has already been deployed**, run `kubectl delete secret audit-g3auto` and `gen3 kube-setup-audit-service` to configure the audit SQS and update the configuration file. REQUIRES Fence 5.1.0 or more recent. OR to disable pulling from a queue, update the configuration file manually to disable "PULL_FROM_QUEUE" (uc-cdis/audit-service#2)
- fence
  - For existing deployments with "ENABLE_AUDIT_LOGS" turned ON, to DISABLE pushing audit logs to an AWS SQS, the configuration "PUSH_AUDIT_LOGS_CONFIG.type" must be changed to "api" (default: "aws_sqs"). If audit-service has never been deployed, no action required. (uc-cdis/fence#923)
  - To ENABLE pushing audit logs to an AWS SQS (REQUIRES audit-service 1.0.0 or more recent), create/update the configuration file's "PUSH_AUDIT_LOGS_CONFIG" field ("type: aws_sqs" (default), and the SQS URL and region can be copied from the audit-service configuration - or run `gen3 sqs info $(gen3 api safe-name audit-sqs)`), see https://github.com/uc-cdis/fence/blob/fec3dd937d68384e86b2ed6f9b53daf0026c2df9/fence/config-default.yaml#L632-L636. Then run `kubectl delete secret fence-config` and `gen3 kube-setup-fence` (uc-cdis/fence#923)

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
## Deployment changes
- audit-service
  - **If a previous version of the audit service has already been deployed**, run `kubectl delete secret audit-g3auto` and `gen3 kube-setup-audit-service` to configure the audit SQS and update the configuration file. REQUIRES Fence 5.1.0 or more recent. OR to disable pulling from a queue, update the configuration file manually to disable "PULL_FROM_QUEUE" (uc-cdis/audit-service#2)
- fence
  - For existing deployments with "ENABLE_AUDIT_LOGS" turned ON, to DISABLE pushing audit logs to an AWS SQS, the configuration "PUSH_AUDIT_LOGS_CONFIG.type" must be changed to "api" (default: "aws_sqs"). If audit-service has never been deployed, no action required. (uc-cdis/fence#923)
  - To ENABLE pushing audit logs to an AWS SQS (REQUIRES audit-service 1.0.0 or more recent), create/update the configuration file's "PUSH_AUDIT_LOGS_CONFIG" field ("type: aws_sqs" (default), and the SQS URL and region can be copied from the audit-service configuration - or run `gen3 sqs info $(gen3 api safe-name audit-sqs)`), see https://github.com/uc-cdis/fence/blob/fec3dd937d68384e86b2ed6f9b53daf0026c2df9/fence/config-default.yaml#L632-L636. Then run `kubectl delete secret fence-config` and `gen3 kube-setup-fence` (uc-cdis/fence#923)

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
## Deployment changes
- audit-service
  - **If a previous version of the audit service has already been deployed**, run `kubectl delete secret audit-g3auto` and `gen3 kube-setup-audit-service` to configure the audit SQS and update the configuration file. REQUIRES Fence 5.1.0 or more recent. OR to disable pulling from a queue, update the configuration file manually to disable "PULL_FROM_QUEUE" (uc-cdis/audit-service#2)
- fence
  - For existing deployments with "ENABLE_AUDIT_LOGS" turned ON, to DISABLE pushing audit logs to an AWS SQS, the configuration "PUSH_AUDIT_LOGS_CONFIG.type" must be changed to "api" (default: "aws_sqs"). If audit-service has never been deployed, no action required. (uc-cdis/fence#923)
  - To ENABLE pushing audit logs to an AWS SQS (REQUIRES audit-service 1.0.0 or more recent), create/update the configuration file's "PUSH_AUDIT_LOGS_CONFIG" field ("type: aws_sqs" (default), and the SQS URL and region can be copied from the audit-service configuration - or run `gen3 sqs info $(gen3 api safe-name audit-sqs)`), see https://github.com/uc-cdis/fence/blob/fec3dd937d68384e86b2ed6f9b53daf0026c2df9/fence/config-default.yaml#L632-L636. Then run `kubectl delete secret fence-config` and `gen3 kube-setup-fence` (uc-cdis/fence#923)

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
## Deployment changes
- audit-service
  - **If a previous version of the audit service has already been deployed**, run `kubectl delete secret audit-g3auto` and `gen3 kube-setup-audit-service` to configure the audit SQS and update the configuration file. REQUIRES Fence 5.1.0 or more recent. OR to disable pulling from a queue, update the configuration file manually to disable "PULL_FROM_QUEUE" (uc-cdis/audit-service#2)
- fence
  - For existing deployments with "ENABLE_AUDIT_LOGS" turned ON, to DISABLE pushing audit logs to an AWS SQS, the configuration "PUSH_AUDIT_LOGS_CONFIG.type" must be changed to "api" (default: "aws_sqs"). If audit-service has never been deployed, no action required. (uc-cdis/fence#923)
  - To ENABLE pushing audit logs to an AWS SQS (REQUIRES audit-service 1.0.0 or more recent), create/update the configuration file's "PUSH_AUDIT_LOGS_CONFIG" field ("type: aws_sqs" (default), and the SQS URL and region can be copied from the audit-service configuration - or run `gen3 sqs info $(gen3 api safe-name audit-sqs)`), see https://github.com/uc-cdis/fence/blob/fec3dd937d68384e86b2ed6f9b53daf0026c2df9/fence/config-default.yaml#L632-L636. Then run `kubectl delete secret fence-config` and `gen3 kube-setup-fence` (uc-cdis/fence#923)

**Review by haraprasadj — APPROVED** [review]
+1

**Pull request merged**
