### PR TITLE
Change `minimalFieldMapping.uid` in brh to `_unique_id`

### PR DESCRIPTION
**Pull request by nss10**
Link to Jira ticket if there is one: [BRH-389](https://ctds-planx.atlassian.net/browse/BRH-389)

### Environments
* qa-brh

### Description of changes
* Updating the `minimalFieldMapping.uid` portal config in qa-brh from `frontend_uid` to `_unique_id`
* Pointing data portal to `fix_datarow-key-issue` branch to include the changes made in this [data-portal PR](https://github.com/uc-cdis/data-portal/pull/1205)

[BRH-389]: https://ctds-planx.atlassian.net/browse/BRH-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services are being downgraded
- portal

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## Deployment changes
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - [PXP-10565]: https://ctds-planx.atlassian.net/browse/PXP-10565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/data-portal/pull/1208)

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## Deployment changes
- portal
  - New portal config options to exclude File nodes from the charts added: use `"graphql.chartNodesExcludeFiles"` to exclude File nodes from graphql chart, or use `"components.index.homepageChartNodesExcludeFiles"` to exclude File nodes from homepage chart. Note both of them are default to `false` so you have to explicitly set them to `true` to enable them (https://github.com/uc-cdis/data-portal/pull/1208)
  - [PXP-10565]: https://ctds-planx.atlassian.net/browse/PXP-10565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ (https://github.com/uc-cdis/data-portal/pull/1208)

**Review by haraprasadj — APPROVED** [review]

**Pull request merged**
