### PR TITLE
(PXP-9639): Use fixed ES aliases for all Jenkins environments

### PR DESCRIPTION
**Pull request by johnfrancismccann**
Jira Ticket: [PXP-9639](https://ctds-planx.atlassian.net/browse/PXP-9639)

### Environments
- jenkins-blood.planx-pla.net
- jenkins-brain.planx-pla.net
- jenkins-dcp.planx-pla.net
- jenkins-genomel.planx-pla.net
- jenkins-new.planx-pla.net
- jenkins-niaid.planx-pla.net

### Description of changes

So that the [ETL test can clean up (i.e. delete) ES indices](https://github.com/uc-cdis/gen3-qa/pull/785) after the tests run and not interfere with the Guppy pod rolling in the `K8sReset` stage of subsequent pipeline runs, use fixed ES aliases for the guppy config for all Jenkins environments. These fixed ES aliases will not be deleted anywhere by the integration tests.

Also, for consistency, rename `etlMapping.yaml` mapping `name`s (i.e. the string used to name aliases) to use a `{jenkins environment}_{index type}` format.

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-new.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Review by haraprasadj — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-genomel.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-new.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [clinical_trials] in studyViewerConfig.dataType not found in etlMapping
- Field error: rowAccessor [cmc_unique_id] not found in index with type clinical_trials
- Field error: Field [brief_summary] in studyViewerConfig.blockFields.listItemConfig not found in etlMapping
- Field error: Field [data_availability_date] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [data_available] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [creator] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [nct_number] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [condition] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [category] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [clinical_trial_website] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping
- Field error: Field [publications] in studyViewerConfig.tableFields.listItemConfig not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- ssjdispatcher
- tube
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-brain.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor
# jenkins-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- audit-service
- awshelper
- fence
- indexd
- mariner
- ws-storage
- peregrine
- pidgin
- portal
- revproxy
- sheepdog
- spark
- tube
- ssjdispatcher
- manifestservice
- wts
- guppy
- sower
- hatchery
- metadata
- dashboard
- requestor

**Pull request merged**
