### PR TITLE
Chore/qa brh access changes

### PR DESCRIPTION
**Pull request by aartivnkt**
Link to Jira ticket if there is one:

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- kayako-wrapper
- metadata
- portal
## :warning: Services are being downgraded
- portal

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- kayako-wrapper
- metadata
- portal
## :warning: Services are being downgraded
- portal

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- kayako-wrapper

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- kayako-wrapper

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- kayako-wrapper

**Review by nss10 — COMMENTED** [review]
LGTM -- Let's Get This Merged!

**Review by nss10 — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- kayako-wrapper
- metadata

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- kayako-wrapper
- metadata

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## :warning: Services on branch
- kayako-wrapper
- metadata

**Comment by aartivnkt** [comment]
Closing this PR, gitops.json changes are merged in this separate PR https://github.com/uc-cdis/gitops-qa/pull/2206/files

**Pull request closed without merging**
