### PR TITLE
chore: updating QA-COVID19 to 2021.01 release version

### PR DESCRIPTION
**Pull request by atharvar28**
https://ctds-planx.atlassian.net/browse/PXP-7449

Updating COVID19 QA to 2021.01 release

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- auspice

**Review by paulineribeyre — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- auspice

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- auspice

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- auspice

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- auspice

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- auspice

**Pull request merged**
