### PR TITLE
adding argocd to qaplanetv1 to test out deploying datadog with argo

### PR DESCRIPTION
**Pull request by EliseCastle23**

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa.planx-pla.net/manifest.json
## :warning: Services on branch
- jenkins
- jenkins-worker
- jenkins-ci-worker
- qabot
- thor

**Review by haraprasadj — COMMENTED** [review]
please test this in some qa environment, preferably in some qa env that is inside qaplanetv2 ... the jenkins and PR pods are all on qaplanetv1. we are already seeing errors saying node does not have enough cpu / memory or there are too many pods.

**Review by AidanHilt — APPROVED** [review]

**Comment by EliseCastle23** [comment]
> 

Hi Hara! I appreciate you double checking on this! Argocd only affects our monitoring (Datadog and Prometheus). It will not have any affect on scaling, node size, pod eviction, etc. 

We will eventually use Argocd to deploy all of Gen3 Helm charts, but for now it only controls our monitoring. Please message me if you have any questions!

**Comment by haraprasadj** [comment]
> > 
> 
> Hi Hara! I appreciate you double checking on this! Argocd only affects our monitoring (Datadog and Prometheus). It will not have any affect on scaling, node size, pod eviction, etc.
> 
> We will eventually use Argocd to deploy all of Gen3 Helm charts, but for now it only controls our monitoring. Please message me if you have any questions!

I would still appreciate not using qaplanetv1 for testing purposes. CI is in a miserable state already and more pressure on that environment is risky.

**Pull request closed without merging**
