### PR TITLE
QADCP_DD_4.0.4

### PR DESCRIPTION
**Pull request by svburke**
Link to Jira ticket if there is one:

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata
- dashboard

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata
- dashboard

**Review by wangfan860 — APPROVED** [review]
👍

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata
- dashboard

**Pull request merged**
