### PR TITLE
TESTING Please ignore

### PR DESCRIPTION
**Pull request by mattreex**
Link to Jira ticket if there is one:

### CODE REVIEW

**Comment by mattreex** [comment]
# gitops.json
## Field error: Field not a datatype in explorerConfig.guppyConfig.dataType not found in ETLmapping
## Field error: Field date_collected in explorerConfig.filters.tabs.fields not found in ETLmapping
## Field error: Field investigator_affiliation in explorerConfig.filters.tabs.fields not found in ETLmapping
## Field error: Field data_description in explorerConfig.filters.tabs.fields not found in ETLmapping
## Field error: Field not a field 1 in explorerConfig.filters.tabs.fields not found in ETLmapping
## Field error: Field not a field 2 in explorerConfig.filters.tabs.fields not found in ETLmapping
## Field error: Field url in explorerConfig.table.fields not found in ETLmapping
## Field error: Field code in explorerConfig.table.fields not found in ETLmapping
## Field error: Field date_collected in explorerConfig.table.fields not found in ETLmapping
## Field error: Field investigator_affiliation in explorerConfig.table.fields not found in ETLmapping
## Field error: Field name in explorerConfig.table.fields not found in ETLmapping
## Field error: Field data_description in explorerConfig.table.fields not found in ETLmapping

**Comment by mattreex** [comment]
# ERRORS FOUND IN gitops.json
### Field error: Field not a datatype in explorerConfig.guppyConfig.dataType not found in ETLmapping
### Field error: Field date_collected in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field investigator_affiliation in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field data_description in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field not a field 1 in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field not a field 2 in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field url in explorerConfig.table.fields not found in ETLmapping
### Field error: Field code in explorerConfig.table.fields not found in ETLmapping
### Field error: Field date_collected in explorerConfig.table.fields not found in ETLmapping
### Field error: Field investigator_affiliation in explorerConfig.table.fields not found in ETLmapping
### Field error: Field name in explorerConfig.table.fields not found in ETLmapping
### Field error: Field data_description in explorerConfig.table.fields not found in ETLmapping

**Comment by mattreex** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- fence

**Comment by PlanXCyborg** [comment]
# ERRORS FOUND IN: qa-covid19.planx-pla.net - gitops.json
### Field error: Field [not a datatype] in explorerConfig.guppyConfig.dataType not found in ETLmapping
### Field error: Field [date_collected] in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field [investigator_affiliation] in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field [data_description] in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field [not a field 1] in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field [not a field 2] in explorerConfig.filters.tabs.fields not found in ETLmapping
### Field error: Field [url] in explorerConfig.table.fields not found in ETLmapping
### Field error: Field [code] in explorerConfig.table.fields not found in ETLmapping
### Field error: Field [date_collected] in explorerConfig.table.fields not found in ETLmapping
### Field error: Field [investigator_affiliation] in explorerConfig.table.fields not found in ETLmapping
### Field error: Field [name] in explorerConfig.table.fields not found in ETLmapping
### Field error: Field [data_description] in explorerConfig.table.fields not found in ETLmapping

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- fence

**Comment by PlanXCyborg** [comment]
# ERRORS FOUND IN: qa-brain.planx-pla.net - gitops.json
### Field error: Field [not a field] in explorerConfig.filters.tabs.fields not found in ETLmapping

**Comment by PlanXCyborg** [comment]
# ERRORS FOUND IN: qa-covid19.planx-pla.net - gitops.json
### Field error: Field [not a field] in explorerConfig.table.fields not found in ETLmapping

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- fence

**Comment by mattreex** [comment]
:

**Comment by PlanXCyborg** [comment]
# qa-brain.planx-pla.net: gitops.json
 :x: ETLMapping errors
- Field error: Field [not a field] in explorerConfig.filters.tabs.fields not found in ETLmapping

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- fence

**Comment by PlanXCyborg** [comment]
# qa-brain.planx-pla.net: gitops.json
 :x: ETLMapping.yaml - gitops.json mismatch
- Field error: Field [not a field] in explorerConfig.filters.tabs.fields not found in ETLmapping

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net: gitops.json
 :x: ETLMapping.yaml - gitops.json mismatch
- Field error: Field [not a field] in explorerConfig.table.fields not found in ETLmapping

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- fence

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [not a field] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-covid19.planx-pla.net/manifest.json
## :warning: Services on branch
- fence

**Pull request closed without merging**
