### PR TITLE
Feat/qa heal

### PR DESCRIPTION
**Pull request by mfshao**
Link to Jira ticket if there is one:

### Environments
- qa-heal

### Description of changes
- deploy searchable tags to qa-heal

### CODE REVIEW

**Review by haraprasadj — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata
- hatchery

**Review by nmetokishlubsky — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata
- hatchery

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata
- hatchery

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- metadata
- hatchery
## Deployment changes
- portal
  - Discovery: introduced a new config section `discoveryConfig.features.search.tagSearchDropdown`, see `portal-config.md` for more info (uc-cdis/data-portal#927)

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- metadata
- hatchery
## Deployment changes
- portal
  - Discovery: introduced a new config section `discoveryConfig.features.search.tagSearchDropdown`, see `portal-config.md` for more info (uc-cdis/data-portal#927)

**Pull request merged**
