### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by mfshao**
Link to Jira ticket if there is one: https://ctds-planx.atlassian.net/browse/HP-623

### Environments
- qa-heal

### Description of changes
- update aws-es-proxy to resolve intermittent aggmds sync job failure

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Review by haraprasadj — DISMISSED** [review]
+1

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal

**Pull request merged**
