### PR TITLE
adding sower service tp qa-ibd

### PR DESCRIPTION
**Pull request by atharvar28**
Adding sower service and sower block to manifest.json

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-ibd.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-ibd.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- dashboard
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- hatchery
- wts
- manifestservice
- guppy
- ssjdispatcher
- metadata
- sower

**Review by xritter1 — APPROVED** [review]

**Review by xritter1 — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-ibd.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-ibd.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- dashboard
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- hatchery
- wts
- manifestservice
- guppy
- ssjdispatcher
- metadata
- sower

**Pull request merged**
