### PR TITLE
qa-jcoin etl nested_props

### PR DESCRIPTION
**Pull request by paulineribeyre**
Link to Jira ticket if there is one:

### Environments
qa-jcoin

### Description of changes
ETL mapping: use nested_props

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-jcoin.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [project_id] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [project_id] in explorerConfig.table.fields not found in etlMapping

**Review by atharvar28 — APPROVED** [review]

**Comment by mbkranz** [comment]
@paulineribeyre  Thanks Pauline! ❤️

**Comment by mbkranz** [comment]
Appreciate it!

**Pull request merged**
