### PR TITLE
Gen3 Monthly Release 2023.04 qa-dcp.planx-pla.net 1679929360

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2023.04 to qa-dcp.planx-pla.net

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping

**Review by haraprasadj — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [_subject_id] in explorerConfig.charts not found in etlMapping

**Pull request merged**
