### PR TITLE
chore(heal): aggregate mds for qa heal

### PR DESCRIPTION
**Pull request by williamhaley**
Link to Jira ticket if there is one:

### Environments

* HEAL QA

### Description of changes

* Enable use of the aggregate MDS APIs

### CODE REVIEW

**Review by xritter1 — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata

**Review by haraprasadj — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- metadata
- hatchery

**Pull request merged**
