### PR TITLE
Verify refresh_token_at_login

### PR DESCRIPTION
**Pull request by nss10**
Link to Jira ticket if there is one: [BRH-390](https://ctds-planx.atlassian.net/browse/BRH-390)

### Environments
* qa-brh

### Description of changes
* Added `workspaceTokenServiceRefreshTokenAtLogin` and updated portal to `5.2.0` to test `data-portal PR-1095`

[BRH-390]: https://ctds-planx.atlassian.net/browse/BRH-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by haraprasadj — DISMISSED** [review]

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Comment by PlanXCyborg** [comment]
# qa-brh.planx-pla.net/manifest.json
## Deployment changes
- portal
  - this change assumes WTS is already a core/central service. The dependency is hereby moved to the homepage (instead of the ./workspace page) (https://github.com/uc-cdis/data-portal/pull/1095)

**Review by swatkatsrazor — APPROVED** [review]

**Pull request merged**
