### PR TITLE
Gen3 Monthly Release 2022.04 qa-heal.planx-pla.net 1650378262

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version 2022.04 to qa-heal.planx-pla.net

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## Deployment changes
- wts
  - This version of WTS requires a DB migration (in cloud-automation deployments, the DB should be migrated automatically) (uc-cdis/workspace-token-service#40)

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- frontend-framework
## Deployment changes
- wts
  - This version of WTS requires a DB migration (in cloud-automation deployments, the DB should be migrated automatically) (uc-cdis/workspace-token-service#40)

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- frontend-framework
## Deployment changes
- wts
  - This version of WTS requires a DB migration (in cloud-automation deployments, the DB should be migrated automatically) (uc-cdis/workspace-token-service#40)

**Comment by PlanXCyborg** [comment]
# qa-heal.planx-pla.net/manifest.json
## :warning: Services on branch
- portal
- frontend-framework
## Deployment changes
- wts
  - This version of WTS requires a DB migration (in cloud-automation deployments, the DB should be migrated automatically) (uc-cdis/workspace-token-service#40)

**Review by haraprasadj — APPROVED** [review]

**Pull request merged**
