### PR TITLE
QA DD 1.5.2 release IBDGC 

### PR DESCRIPTION
**Pull request by xritter1**
Link to Jira ticket if there is one: https://ctds-planx.atlassian.net/browse/PXP-7400

Environments
https://ibdgc.datacommons.io/

Description of changes
- New DD release 1.5.2: Fix enums in operation_ad property in Surgery node; fix type in GVI node

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-ibd.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- dashboard
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- hatchery
- wts
- manifestservice
- guppy
- ssjdispatcher
- metadata

**Review by svburke — APPROVED** [review]

**Review by themarcelor — APPROVED** [review]
+1

**Comment by PlanXCyborg** [comment]
# qa-ibd.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- dashboard
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- hatchery
- wts
- manifestservice
- guppy
- ssjdispatcher
- metadata

**Review by atharvar28 — APPROVED** [review]

**Comment by PlanXCyborg** [comment]
# qa-ibd.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- dashboard
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- hatchery
- wts
- manifestservice
- guppy
- ssjdispatcher
- metadata

**Pull request merged**
