### PR TITLE
Updating QA Environment integration202105 qa-dcp.planx-pla.net 1618329513

### PR DESCRIPTION
**Pull request by PlanXCyborg**
Applying version integration202105 to qa-dcp.planx-pla.net

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata
- dashboard

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# qa-dcp.planx-pla.net/manifest.json
## :warning: Services on branch
- arborist
- fence
- indexd
- peregrine
- pidgin
- revproxy
- sheepdog
- portal
- spark
- tube
- guppy
- sower
- hatchery
- wts
- manifestservice
- ssjdispatcher
- metadata

**Review by jingh8 — APPROVED** [review]

**Pull request merged**
