### PR TITLE
Chore(qa): Make jenkins envs compliant with mariner

### PR DESCRIPTION
**Pull request by jingh8**
Link to Jira ticket if there is one:
https://ctds-planx.atlassian.net/browse/PXP-8306

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-genomel.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-genomel.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-genomel.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-genomel.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-blood.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping
- Field error: Field [data_type] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-brain.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [veteran_status] in explorerConfig.filters.tabs.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-dcp.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.table.fields not found in etlMapping

**Comment by PlanXCyborg** [comment]
# jenkins-genomel.planx-pla.net
 :x: etlMapping.yaml - gitops.json mismatch
- Field error: Field [data_type] in explorerConfig.filters.tabs.fields not found in etlMapping
- Field error: Field [data_format] in explorerConfig.filters.tabs.fields not found in etlMapping

**Review by atharvar28 — APPROVED** [review]

**Review by themarcelor — APPROVED** [review]
+1

**Pull request merged**
